-- =============================================================================
-- Q_COCKPIT — query pour DATASOURCE Tagetik (cockpit), forme "en ligne" FST-ready
-- =============================================================================
-- Datasource -> matrice multidim. Rien de pré-calculé : le FST calcule CA/EBITDA/marge.
--   Finance    = comptes P&L réels (dont 6231 = dépense acquisition)
--   Commercial = comptes STATISTIQUES : STAT_LEAD/CAND/ADMIS/INSC/EFF
-- Membres calculés Tagetik : Marge % = EBITDA/CA ; CAC = 6231 / STAT_INSC.
-- Maille fine : finance = ENTITY×ACCOUNT×EXERCICE×PERIOD ;
--               commercial = + PROGRAMME×AN_ETUDE×MODALITE. Non applicable = 'GEN'.
-- =============================================================================
SELECT ENTITY, 'GEN' AS PROGRAMME, 'GEN' AS AN_ETUDE, 'GEN' AS MODALITE,
       ACCOUNT, EXERCICE, CAST(PERIOD AS VARCHAR(10)) AS PERIOD, 'ACT' AS VERSION,
       SUM(AMOUNT) AS AMOUNT
FROM AW_002_000004_000001
GROUP BY ENTITY, ACCOUNT, EXERCICE, CAST(PERIOD AS VARCHAR(10))

UNION ALL
SELECT ENTITY, PROGRAMME, AN_ETUDE, MODALITE, 'STAT_LEAD', EXERCICE,
       CAST(PERIODE AS VARCHAR(10)), 'ACT', SUM(VOL_LEAD)
FROM AW_002_000002_000001
GROUP BY ENTITY, PROGRAMME, AN_ETUDE, MODALITE, EXERCICE, CAST(PERIODE AS VARCHAR(10))

UNION ALL
SELECT ENTITY, PROGRAMME, AN_ETUDE, MODALITE, 'STAT_CAND', EXERCICE,
       CAST(PERIODE AS VARCHAR(10)), 'ACT', SUM(VOL_CAND)
FROM AW_002_000002_000001
GROUP BY ENTITY, PROGRAMME, AN_ETUDE, MODALITE, EXERCICE, CAST(PERIODE AS VARCHAR(10))

UNION ALL
SELECT ENTITY, PROGRAMME, AN_ETUDE, MODALITE, 'STAT_ADMIS', EXERCICE,
       CAST(PERIODE AS VARCHAR(10)), 'ACT', SUM(VOL_ADMIS)
FROM AW_002_000002_000001
GROUP BY ENTITY, PROGRAMME, AN_ETUDE, MODALITE, EXERCICE, CAST(PERIODE AS VARCHAR(10))

UNION ALL
SELECT ENTITY, PROGRAMME, AN_ETUDE, MODALITE, 'STAT_INSC', EXERCICE,
       CAST(PERIODE AS VARCHAR(10)), 'ACT', SUM(VOL_NEW)
FROM AW_002_000002_000001
GROUP BY ENTITY, PROGRAMME, AN_ETUDE, MODALITE, EXERCICE, CAST(PERIODE AS VARCHAR(10))

UNION ALL
SELECT ENTITY, PROGRAMME, AN_ETUDE, MODALITE, 'STAT_EFF', EXERCICE,
       CAST(PERIODE AS VARCHAR(10)), 'ACT', SUM(VOL_EFF)
FROM AW_002_000002_000001
GROUP BY ENTITY, PROGRAMME, AN_ETUDE, MODALITE, EXERCICE, CAST(PERIODE AS VARCHAR(10));
