-- =============================================================================
-- VUE CADRAGE — LEVIERS DE GROUPE (pivot)  (corps SELECT ; SAP HANA)
-- Source : AW_002_000001_000001 (cadrage)
-- Les leviers sont stockés en LONG (1 ligne = 1 PARAMETRE x VERSION) → on pivote
-- en 1 ligne par VERSION (V01/V02/V03…), colonnes = leviers. ENTITY = 'GRP'.
-- NB : le coefficient prix par marque (HYP_PRICE_COEF) est à un autre grain
--      (ENTITY = <marque>_REF, VERSION = GEN) → voir V_CADRAGE_PRICE_COEF plus bas.
-- =============================================================================
SELECT
    t.SCENARIO, t.PERIODE, t.VERSION,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_ACQ_BUD'       THEN t.MEASURE END) AS LEV_ACQ_BUD,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_BRAND_BUD'     THEN t.MEASURE END) AS LEV_BRAND_BUD,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_PRICE'         THEN t.MEASURE END) AS LEV_PRICE,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_CNV_LEAD_CAND' THEN t.MEASURE END) AS LEV_CNV_LEAD_CAND,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_CNV_ADM_INS'   THEN t.MEASURE END) AS LEV_CNV_ADM_INS,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_PASS_RATE'     THEN t.MEASURE END) AS LEV_PASS_RATE,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_INFL_EXT'      THEN t.MEASURE END) AS LEV_INFL_EXT,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_SALARY'        THEN t.MEASURE END) AS LEV_SALARY,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_FTE_PERM'      THEN t.MEASURE END) AS LEV_FTE_PERM,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_PRODUCTIVITY'  THEN t.MEASURE END) AS LEV_PRODUCTIVITY,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_STRUCT_COST'   THEN t.MEASURE END) AS LEV_STRUCT_COST,
    MAX(CASE WHEN t.PARAMETRE = 'HYP_FILE_FEE'      THEN t.MEASURE END) AS FILE_FEE
FROM AW_002_000001_000001 t
WHERE t.ENTITY = 'GRP'
GROUP BY t.SCENARIO, t.PERIODE, t.VERSION

-- --- V_CADRAGE_PRICE_COEF (coeff prix par marque) : à créer comme vue séparée ---
-- SELECT t.ENTITY, t.MEASURE AS PRICE_COEF
-- FROM AW_002_000001_000001 t
-- WHERE t.PARAMETRE = 'HYP_PRICE_COEF'
