-- Efficience d'acquisition : CPL (cout par lead payant) et CAC (cout par inscrit)
CREATE OR REPLACE VIEW V_CAC AS
SELECT EXERCICE, SUBSTR_BEFORE(ENTITY,'_') AS MARQUE,
    SUM(DEPENSE_ACQ)   AS DEPENSE_ACQ,
    SUM(VOL_LEAD_PAY)  AS LEADS_PAYANTS,
    SUM(VOL_NEW)       AS INSCRITS,
    SUM(DEPENSE_ACQ) / NULLIF(SUM(VOL_LEAD_PAY),0) AS CPL,
    SUM(DEPENSE_ACQ) / NULLIF(SUM(VOL_NEW),0)      AS CAC
FROM AW_002_000002_000001
GROUP BY EXERCICE, SUBSTR_BEFORE(ENTITY,'_');
