-- Funnel de conversion : lead -> candidat -> admis -> inscrit + taux (Socle CRM)
CREATE OR REPLACE VIEW V_FUNNEL AS
SELECT EXERCICE, SUBSTR_BEFORE(ENTITY,'_') AS MARQUE,
    SUM(VOL_LEAD)  AS LEADS, SUM(VOL_CAND) AS CANDIDATS,
    SUM(VOL_ADMIS) AS ADMIS, SUM(VOL_NEW)  AS INSCRITS,
    SUM(VOL_CAND)  / NULLIF(SUM(VOL_LEAD),0)  AS TX_LEAD_CAND,
    SUM(VOL_ADMIS) / NULLIF(SUM(VOL_CAND),0)  AS TX_CAND_ADMIS,
    SUM(VOL_NEW)   / NULLIF(SUM(VOL_ADMIS),0) AS TX_ADMIS_INSC
FROM AW_002_000002_000001
GROUP BY EXERCICE, SUBSTR_BEFORE(ENTITY,'_');
